os: linux
dist: focal
language: python

python:
  - "3.11"

addons:
  apt:
    packages:
    - libcups2-dev

services:
- mysql

branches:
  only:
  - develop

install:
- pip install --upgrade pip
- pip install -r requirements.txt
- pip install flake8
- pip install coveralls

before_script:
- flake8 edc_prn
- mysql -e 'create database edc character set utf8;'

script:
- python manage.py check
- coverage run --source=edc_prn manage.py test

after_success:
- coveralls
